# Generated by Django 3.0.5 on 2023-05-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_donor_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('purpose', models.CharField(max_length=20)),
                ('doctor', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('bg', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='pdfs/patients/')),
                ('hosp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='login.Hospitals')),
            ],
        ),
    ]
