# Generated by Django 3.0.5 on 2023-06-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_bankstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
