# Generated by Django 3.0.5 on 2023-06-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20230603_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Bloodbank')),
                ('ndonor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('nbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Bloodbank')),
                ('npatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Patient')),
            ],
        ),
    ]
