# Generated by Django 3.0.5 on 2023-06-14 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_notification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='nbank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Bloodbank'),
        ),
    ]
