# Generated by Django 3.0.5 on 2023-06-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20230619_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.CharField(max_length=20),
        ),
    ]
