# Generated by Django 3.0.5 on 2023-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20230619_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.CharField(default='Kannur', max_length=20),
            preserve_default=False,
        ),
    ]
