# Generated by Django 3.0.5 on 2023-06-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_hospital_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reason',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
