# Generated by Django 3.0.5 on 2023-06-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_remove_notification_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='certificate',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
