# Generated by Django 3.0.5 on 2023-06-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_notification_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='certificate',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
