# Generated by Django 3.0.5 on 2023-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20230628_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='certificate',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reason',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
