# Generated by Django 3.0.5 on 2023-05-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='user',
            new_name='uuser',
        ),
    ]
