# Generated by Django 3.0.5 on 2023-05-26 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20230525_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='document',
            field=models.FileField(upload_to='pdfs/donor/'),
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='pdfs/hospital/')),
                ('uuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('document', models.FileField(upload_to='pdfs/bloodbank/')),
                ('uuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloodbank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
