# Generated by Django 3.0.5 on 2023-05-27 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20230526_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
