# Generated by Django 3.0.5 on 2023-05-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_patients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitals',
            new_name='Hospital',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
