# Generated by Django 3.0.5 on 2023-05-29 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20230528_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap', models.IntegerField(default=5)),
                ('an', models.IntegerField(default=5)),
                ('bp', models.IntegerField(default=5)),
                ('bn', models.IntegerField(default=5)),
                ('abp', models.IntegerField(default=5)),
                ('abn', models.IntegerField(default=5)),
                ('op', models.IntegerField(default=5)),
                ('on', models.IntegerField(default=5)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankstock', to='login.Bloodbank')),
            ],
        ),
    ]
